name: Build on Windows
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: choco install python3
      - run: 
          echo Add other actions to build,
          echo test, and deploy your project.
