name: Build on Windows
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: choco install gh
      - run: gh version
          echo Add other actions to build,
          echo test, and deploy your project.
