name: Build on Windows
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
     - run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module NTFSSecurity, PSScriptAnalyzer
          Get-Item c:\users | Get-NTFSAccess
